kind = "web"
previewPath = "/"
title = "FTM-CODER-AI"
version = "1.0.0"
id = "artifacts/ftm-coder-ai"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22177

[services.development]
run = "pnpm --filter @workspace/ftm-coder-ai run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ftm-coder-ai", "run", "build" ]
publicDir = "artifacts/ftm-coder-ai/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22177"
BASE_PATH = "/"
